### ISSUE TITLE
Indsamling af information om blærekræft

### ISSUE THREAD

**Issue by LordCrisp** [SleipnerTechnologies/saftens-bekaempelse#8]
Saml information om blærekræft..

Informations emner sorteres efter umiddelbar prioitet
"Hvad skal man være opmærksom på"
"Årsag til blærekræft"
"Hvad kan man gøre for at forebygge og bekæmpe det"
"Behandligen af blærekræft"

Derefter statistikker og yderligere viden, alt efter hvor meget der er "plads" til, uden at det bliver for tungt

#6

**Comment by Plz-Knudsen** [comment]
https://www.cancer.dk/blaerekraeft-blaerecancer/
